### ISSUE TITLE
Survey campaign popup not respecting "do not show again" option?

### ISSUE THREAD

**Issue by Stephen-ONeil** [TBS-EACPD/infobase#577]
My use of local storage may not be as sticky as I thought. Something to look in to before the next time we enable that popup campaign.

**Comment by ktw1016** [comment]
@GarvinH is this one fixed??

**Comment by GarvinH** [comment]
I never ran into this issue so I can't say if this is still present.

**Comment by Stephen-ONeil** [comment]
It never happened on my dev builds, but multiple people (myself included) saw it in prod. Couldn't recreate it consistently before the end of the survey campaign though. Won't really know until we next enable it in prod for an extended period I think.

**Comment by Stephen-ONeil** [comment]
This is fixed now, if I remember right it was because I forgot which unit of time was returned by Date.now(), oops.

**Comment by AlexCLeduc** [comment]
I'm still getting repeated popups despite doing hard refreshes and filling out the survey or pressing the other buttons

**Comment by GarvinH** [comment]
Is there a way to replicate that?

**Comment by AlexCLeduc** [comment]
After resetting localstorage and doing another hard refresh, I've only been able to trigger it once. Maybe it was just some kind of caching thing

**Comment by Stephen-ONeil** [comment]
Guess we'll close again. If it occurs the next time the survey popup campaign is active we'll just treat that as a new issue.
